const getRandomFruitsName = require('random-fruits-name')
console.log(getRandomFruitsName()) // Apple - English is default language
console.log(getRandomFruitsName('en')) 
console.log(getRandomFruitsName('en')) 
console.log(getRandomFruitsName('en')) 
console.log(getRandomFruitsName('en')) 
console.log(getRandomFruitsName('en')) 
console.log(getRandomFruitsName('en')) 
console.log(getRandomFruitsName('en')) 
console.log(getRandomFruitsName('en')) 
